version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:
    external: true
