services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    env_file:
      - .env

networks:
  mynetwork:
    external: true